### ISSUE TITLE
suggestion: add position information to the positioned node

### ISSUE THREAD

**Issue by yairEO** [Simonwep/nanopop#12]
I need the `reposition` method to add information regarding the placement of the *popper* element because I want to use it as tooltips and I need to know where are the poppers places so I could render the correct triangle tip which will point to the side which triggered the tooltip

**Comment by Simonwep** [comment]
What about using the return value of the `reposition` function?
> Calling popper.update(...) or reposition(...) both returns a position-pair (For example "te" for Top-End) or null based on if it was possible to find a position for the popper without clipping it.

**Comment by yairEO** [comment]
Ha right. Good idea.
