### ISSUE TITLE
Position "bottom-middle" not behaving as expected

### ISSUE THREAD

**Issue by panphora** [Simonwep/nanopop#2]
When using an `inline-block` button and a wide dropdown element, with Nanopop configured to have the dropdown appear in the `"bottom-middle"`, I instead see the dropdown appearing on the right side of the button.

```
NanoPop(reference, popper, {
  position: "bottom-middle"
});
```

<img width="464" alt="Screen Shot 2020-05-29 at 11 41 38 AM" src="https://user-images.githubusercontent.com/364330/83278330-6e445500-a1a1-11ea-9b1c-3dede570473d.png">

I created an example to showcase the code: https://codepen.io/panphora/pen/RwWXwWw

Can you help me figure out how to get the dropdown to appear below the button and in the middle?

**Comment by Simonwep** [comment]
Ugh, can't edit the codepen without signing up...

As stated in the README, the default "clipping-box" is `document.documentElement` which is in your case `html` so you have to set the height of body / html to 100 to make room for the popper:

```css
body,
html {
  height: 100vh;
}
```

In your case `update` returns `rs` for right-start as the html-elements ends right at the bottom of `button` :)

**Comment by Simonwep** [comment]
I've update the README with a note about this situation, in case others run into this kind of problem as well :)
