### ISSUE TITLE
error nanopop@2.4.0: The engine "node" is incompatible with this module. Expected version "^20". Got "18.18.2" vercel

### ISSUE THREAD

**Issue by clinton9ice** [simonwep/nanopop#27]
So i was trying to deploy my project but locally it builds well cause i'm guessing cause i have the current node version but on vercel, i get the above error i had to check to see you specified the node version to be ^20 which is still in beta mode.

How can i go around this ?

```  js
 "engines": {
        "node": "^20"
    },
   ```

**Comment by evalienigena** [comment]
Hey there, I had a similar problem. 

I'm using AWS Amplify to deploy my app and the same error popped up. I'm using yarn as a package manager.
In my case, I went to my app's **Build Settings** in Amplify and added the option `--ignore-engines` to my build command. The full command would be `yarn install --ignore-engines`.

I think that you can update your build command similarly on Vercel (check: [https://vercel.com/docs/deployments/configure-a-build](https://vercel.com/docs/deployments/configure-a-build)).

Hope this helps! 😄

**Comment by clinton9ice** [comment]
Hi @evalienigena thanks. I was able to make a temporary fix by upgrading my node version on vercel to 20 but however i don't think it's idealistic since node 20 is still in beta mode, what do you think ?

**Comment by sea-yu** [comment]
Hello, I encountered the same problem. Can the author remove the restriction of node > 20? Thanks!!!

**Comment by hc9527** [comment]
依赖这么高，你在搞什么飞机

**Comment by elvisWEB** [comment]
> 依赖这么高，你在搞什么飞机

The reliance is so high, what kind of plane are you doing?

**Comment by MechaGirls** [comment]
nanopop@2.4.0: The engine "node" is incompatible with this module. Expected version "^20". Got "16.15.0"

搞什么飞机✈️，nodejs版本需要这么高

**Comment by smalldice** [comment]
你只支持node20以上你发个major版本啊 发个毛的minor

**Comment by smalldice** [comment]
Why don't you publish a MAJOR version for this breaking change???
```json
"engines": {
      "node": "^20"
},
```

**Comment by S-mohan** [comment]
哎，antvue依赖这个，我们虚机升不了20，害的我浪费一下午时间

**Comment by S-mohan** [comment]
This update, bad reviews

**Comment by shawn-web** [comment]
同样的问题，大家有解决办法没？

**Comment by simonwep** [comment]
Node v20 is the current LTS version. Either upgrade or use a previous version.

**Comment by simonwep** [comment]
But I can remove the engine restriction since it only matters for development if you have good reasons for it...

**Comment by simonwep** [comment]
I'll revert the change of fixing the engine, just keep in mind that being affected by any new release of one of your dependencies is a clear sign that you're doing something wrong in your dependency management. You should take care of that, see https://github.com/axios/axios/issues/5026
