### ISSUE TITLE
forceApplyOnFailure missed in v2? How now to handle manually positions of element?

### ISSUE THREAD

**Issue by 7iomka** [Simonwep/nanopop#7]
Hi, I see that forceApplyOnFailure missed in v2
How now to handle manually positions of element?
For example, I now that an element need to have position 'bottom-end'.
if the element does not fit into the calculated area to take the desired positioning, your plugin uses positionFlipOrder.
if the element does not fit in any of the existing positionFlipOrder variant - the element receive top: 0; left: 0;
Is it possible to somehow do so that the element in this case simply does not have anything? That is, to remove any inline styles? In this case, I would be able to set position with css only.

**DEMO: https://codesandbox.io/s/practical-pond-zsump?file=/src/App.js**

As a progressive improvement, I would consider not removing / resetting to 0 - all positioning styles, but only those that are not compromised. For example if position is 'bottom-end', and vertically element anyway is in normal rythm, but only have problems with horizontally position, that solution is only to remove left: XX from inline styles, but leave top: YY.
Because in this case, I could simply set a fallback using css: left: 0; right: 0; and element is fullwidth pisitioned.

Thanks!

**Comment by Simonwep** [comment]
So this is available since `2.1.0` :)
